services:
  app:
    image: forumynov
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /app
    command: ["/app/forumynov"]
#    volumes:
#      - ./database:/app/database
